name: Generate JWT Token
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
jobs:
  generate-jwt-token:
    runs-on: ubuntu-latest
    steps:
    - name: Generate JWT Token
      run: |
        RESP=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=my-choice-of-audience")
        echo $RESP

