name: Generate JWT Token
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
jobs:
  generate-jwt-token:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    - name: Generate JWT Token
      run: |
        RESP=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=my-choice-of-audience")
        JWT=$(echo $RESP | jq -r .value)
        JWT_PAYLOAD=$(echo $JWT | cut -d. -f2)
        echo $JWT_PAYLOAD | jq

