name: Generate JWT Token
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
jobs:
  generate-jwt-token:
    runs-on: ubuntu-latest
    steps:
    - name: Generate JWT Token
      run: |
        JWT=$(echo -n '{"sub": "user123", "exp": 1630438400}' | openssl dgst -binary -sha256 -hmac "${{ secrets.GIT_TOKEN }}" | openssl base64)
        echo "JWT Token: $JWT"

